services:
  backend:
    image: ai-productivity-dashboard
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: taskmaster-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: taskmaster-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  test-runner:
    image: ai-productivity-dashboard
    container_name: taskmaster-test-runner
    depends_on:
      - test-db
    environment:
      PYTEST_CURRENT_TEST: "True"
      LIMITER: "False"
    env_file:
      - .env.test
    volumes:
      - ./backend:/app
    command: >
      sh -c "sleep 3 && pytest tests/"

  test-db:
    image: postgres:15
    container_name: taskmaster-test-db
    restart: always
    ports:
      - "5433:5432"  
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_test_data:/var/lib/postgresql/data


volumes:
  postgres_data:
  postgres_test_data:
