services:
  backend:
    image: ai-productivity-dashboard
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: taskmaster-backend
    ports:
      - "8000:8000"
    environment:
      RUNNING_IN_DOCKER: "true"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: taskmaster-db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"

  test-runner:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: taskmaster-test-runner
    depends_on:
      - test-db
    environment:
      PYTEST_CURRENT_TEST: "True"
      LIMITER: "False"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      RUNNING_IN_DOCKER: "true"
    working_dir: /app
    volumes:
      - ./backend:/app
    command: >
      sh -c "sleep 3 && pytest --cov=. --cov-report=xml"


  test-db:
    image: postgres:15
    container_name: taskmaster-test-db
    restart: always
    ports:
      - "5433:5432"  
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_test_data:/var/lib/postgresql/data


volumes:
  postgres_data:
  postgres_test_data:
