services:
  backend:
    image: ai-productivity-dashboard
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: taskmaster-backend-prod
    ports:
      - "8000:8000"  
    env_file:
      - ./backend/.env.prod
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: taskmaster-db-prod
    restart: always
    env_file:
      - ./backend/.env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"  

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        ENV_FILE: .env.prod
    container_name: taskmaster-frontend-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend:/app
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend

volumes:
  postgres_data:
