services:
  backend:
    image: ai-productivity-dashboard
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: taskmaster-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: taskmaster-db
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        ENV_FILE: .env
    container_name: taskmaster-frontend
    ports:
      - "5173:80"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  test-runner:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: taskmaster-test-runner
    env_file:
      - ./backend/.env.test
    depends_on:
      - test-db
    working_dir: /app
    volumes:
      - ./backend:/app
    command: >
      sh -c "sleep 3 && pytest --cov=. --cov-report=xml"


  test-db:
    image: postgres:15
    container_name: taskmaster-test-db
    restart: always
    ports:
      - "5433:5432"  
    env_file:
      - ./backend/.env.test
    volumes:
      - postgres_test_data:/var/lib/postgresql/data


volumes:
  postgres_data:
  postgres_test_data:
